baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Hugo Profile"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true


params:
  title: "Brittany Pittman"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"
  
  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Brittany Pittman" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableachievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Brittany Pittman."
    content: "I am a PhD candidate at Toronto Metropolitan University (formerly Ryerson University) in the Department of Mathematics. My research interests include graph searching, pursuit-evasion games, and Ramsey theory."
    image: /images/profile.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "CV"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-orcid
          url: http://orcid.org/0000-0001-7700-4382
      customIcons:
        - icon: /scholar.png
          url: "https://scholar.google.com/citations?hl=en&authuser=1&user=quIVPiwAAAAJ"


  # Experience
  experience:
    enable: true
    title: "Teaching"
    items:
      - job: "Per Course Instructor"
        company: "Grenfell Campus, Memorial University of Newfoundland"
        date: "September 2023 - present"
        content: |
          - Fall 2023: Math1001 Calculus II
          - Winter 2024: Math1001 Calculus II and Math4340 Combinatorial Analysis
      - job: "Teaching Assistant"
        company: "Toronto Metropolitan University"
        date: "September 2023 - present"
        content: |
          - Winter 2023: MTH314 Discrete Mathematics for Engineers and MTH607 Graph Theory
          - Fall 2022: MTH 110 Discrete Mathematics
          - Winter 2022: MTH314 Discrete Mathematics for Engineers and MTH607 Graph Theory
          - Fall 2021: MTH 110 Discrete Mathematics
          - Fall 2020: MTH 110 Discrete Mathematics

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "PhD in Mathematial Modelling and Methods (in progress)"
        school:
          name: "Toronto Metropolitan University"
        date: "2020-2024"
        content: |-
            - Supervisors:  
            - Research areas:
      - title: "Master of Science in Mathematics"
        school:
          name: "Memorial University of Newfoundland"
        date: "2018-2020"
        content: |-
            - Supervisors:  
            - Research area: The watchman's walk problem on directed graphs.
        featuredLink:
          enable: true
          name: "Thesis"
          url: "https://research.library.mun.ca/14628/1/thesis.pdf"
      - title: "Bachelor of Science in Computational Mathematics"
        school:
          name: "Grenfell Campus, Memorial University of Newfoundland"
        date: "2014-2018"

  # achievements
  achievements:
    enable: true
    title: "Publications"
    items:
      - title: The Localization Game on Oriented Graphs
        content: (with A. Bonato, R. Cushman, and T. Marbach) Discrete and Applied Mathematics
        url: https://arxiv.org/pdf/2208.07788.pdf
      - title: The localization capture time of a graph
        content: (with N. Behague, A. Bonato, M. Huggan and T. Marbach) Theoretical Computer Science, 911 (2022), 80-91.
        url: https://brittanypittman.com/files/CaptureTime.pdf
      - title: The watchman’s walk problem on directed graphs
        content: (with Danny Dyer and Jared Howell), Australasian Journal of Combinatorics 80:2 (2021).
        url: https://ajc.maths.uq.edu.au/pdf/80/ajc_v80_p197.pdf


  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    email: brittany.pittman@torontomu.ca
    btnName: Email
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    socialNetworks:
      linkedin: https://linkedin.com
      twitter: https://twitter.com
      instagram: https://instagram.com
      facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>